INSERT INTO ikp_tasks (CTASKNAME,ITASKPERIOD,DTASKFROMDT,DTASKFROMTM,ITASKFREQUENCY,ITASKINTERVAL,ITASKSIDE,BTASKRUNNING) 
VALUES('Тестовое задание',0,TO_DATE('2020-11-16 11:26:23', 'YYYY-MM-DD HH24:MI:SS'),TO_DATE('2020-11-16 11:26:23', 'YYYY-MM-DD HH24:MI:SS'),0,1,0,1);

INSERT INTO ikp_task_events (IEVENTTASKID,IEVENTNPP,CEVENTNAME,IEVENTTYPE,IEVENTPRESETID,LEVENTTEXT,CEVENTINDIR,CEVENTOUTDIR,CEVENTARHDIR,BEVENTENABLED,IEVENTFILEDIR)
VALUES(1,2,'Проверочное действо 1',1,NULL,'BEGIN'||CHR(10)||'  IKP_DEBUG.LogIt(IKP_DEBUG.lvlDEBUG,''test event 1'');'||CHR(10)||'END;',NULL,NULL,NULL,1,-1);

COMMIT;